smith-taher/FairGrounds

.gitignore
db.js
fairgroundsDatabaseCreation.sql
package-lock.json
package.json

@smith-taher @rfpoulos 👀 on the db creation along with db.js file for future connectivity.

Added sql file to create db and added db.js for connections

---

frontend.js
index.html
style.css

@rcackerley @smith-taher toggles between viewable and not viewable.

toggles between doms

---

fairgrounds.sql
server.js

@smith-taher @rfpoulos quick PR for the add article function to unify our code before standup.

added function to add article to the db

---

server.js

@rcackerley @smith-taher here are some sample routes.  I haven't written the handlers yet.  Ultimately there needs to be a route for a "ratings" get request, right?

lots of routes

---

frontend.js
package-lock.json
package.json

👀 @smith-taher @rfpoulos added a login function to the frontend.js to talk to the server.js / will implement the return once i have written the server response.

Added login function to frontend.js

---

fairgrounds.sql
server.js

@rcackerley @smith-taher I’m having a hell of a time getting the psql database to run locally, so I haven’t really been able to test anything.  I changed a couple of value requirements in the user database (serial id, requireing a username, password, email, ect.) . If possible, pls try and clone the code and run locally.  I'll work with a TA to get the database to start working on my machine sometime today.

get user handler

---

frontend.js
login.html
scripts/AuthController.js
server.js
stylesheets/style.css

@smith-taher @rfpoulos ok, round two with hopefully alot less merge conflicts

Added token auth

---

server.js

@smith-taher @rcackerley adds delete handlers.

adds delete handlers

---

README.md

@rcackerley @smith-taher This is a readme on how the database is set up and how to format API requests.  If this is good/accurate, I propose every time we change either anything in the DB or in DB requests, we update the documentation.

Rfpoulos patch 1

---

server.js

@rcackerley @smith-taher Makes rejection of incoming objects come from the database requirements, not what we hard coded.

the database rejects certain types of incoming objects, not the server

---

public/scripts/AuthController.js
public/style.css

@rfpoulos @smith-taher - quick PR for updated login redirected and adding some style tweaks to navbar

login redirect now working

---

fairgrounds.sql

sql database

---

public/scripts/AuthController.js

@rfpoulos @smith-taher Had a typo that i fixed for login

Fixed typo that caused login bug

---

public/frontend.js
server.js

@rfpoulos @smith-taher Added some functions for token passing

Added functions for Token Passing

---

db.js
dbexport.pgsql
public/index.html
public/ratings.js
public/style.css
server.js

@rcackerley 
@rfpoulos 
I still need to format the skip button and add the Fair and Unfair buttons.

Article populates when Rate Article button is clicked

---

public/ratings.js

Randomly generated article renders when 'Rate Article' button, 'Skip'… button, 'Fair' button, or 'Unfair' button is clicked.
@rcackerley 
@rfpoulos

Random rate article and skip button

---

.gitignore
package-lock.json
package.json
server.js

@rcackerley @smith-taher adds articles uniquely, has adaptable host location.

adds unique articles

---

public/frontend.js
public/scripts/AuthController.js
public/style.css
server.js

@smith-taher @rfpoulos Here's login completed.

Login continued

---

server.js

@smith-taher @rfpoulos round 2 for this. Fixed the bug where you dont get a token when you create an account

Fixed bug that wouldnt send token on acct creation

---

.env
db.js
server.js

@smith-taher @rfpoulos Added a function for Joel to use in order to get the ID from the token

added function for getting ID from token for Joel

---

package-lock.json
package.json
server.js

@rfpoulos @smith-taher Here's the added bcrypt functionality. You will have to wipe your user table to get it all working since yopur old users passwords arent encrypted.

added bcrypt functionality

---

.env
fairgrounds.sql
public/frontend.js
server.js

sql database update

---

server.js

troubleshhot
